version: "3.8"

services:
    php:
        image: php:8.3.19-apache-bookworm-rewrite
        build: .
        ports:
            - "86:80"
        volumes:
            - .:/var/www/html:ro
            - ./php.ini:/usr/local/etc/php/php.ini:ro
        depends_on:
            - mysql

    mysql:
        image: mysql:9.2.0-oraclelinux9
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: ql_cuahanggiay
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        command: --sql_mode="STRICT_TRANS_TABLES"
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
            - ./DatabaseServer/ql_cuahanggiay.sql:/docker-entrypoint-initdb.d/ql_cuahanggiay.sql:ro

    phpmyadmin:
        image: phpmyadmin:5.2.2-apache
        environment:
            PMA_HOST: mysql
            PMA_USER: user
            PMA_PASSWORD: password
        ports:
            - "8080:80"
        depends_on:
            - mysql

volumes:
    mysql-data:
